---
- name: HAProxy | Ensure HAProxy is installed.
  package: name=haproxy state=present

- name: HAProxy | Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no

- name: HAProxy | Set HAProxy version.
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: HAProxy | Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: HAProxy | Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes

- name: HAProxy | Create SSL directory folder
  file:
    path: "{{ haproxy.certs_path }}"
    owner: haproxy
    group: haproxy
    mode: 0755
    state: directory

- name: HAProxy | Install SSL certificates
  copy:
    dest: "{{ haproxy.certs_path }}/{{ item.key }}.crt"
    content: "{{ item.value.content }}"
    mode: 0644
  with_dict: "{{ vault_haproxy.certs | default({}) }}"
